/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/goomba/animated_goomba_super_mario_bros.glb -o src/game/components/GoombaModel.tsx -r public 
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-goomba-super-mario-bros-3c91cc4ac8144d82a05309679a3dbbd5
Title: Animated Goomba (Super Mario Bros)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['Left_Foot_14_-_Default_0']: THREE.Mesh
    ['Left_Foot_07_-_Default_0']: THREE.Mesh
    ['Right_Foor_14_-_Default_0']: THREE.Mesh
    ['Right_Foor_07_-_Default_0']: THREE.Mesh
    ['Body_07_-_Default_0']: THREE.Mesh
    ['Head_10_-_Default_0']: THREE.Mesh
    Head_1_0: THREE.Mesh
    ['Head_15_-_Default_0']: THREE.Mesh
    ['Head_03_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['14_-_Default']: THREE.MeshStandardMaterial
    ['07_-_Default']: THREE.MeshStandardMaterial
    ['10_-_Default']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['15_-_Default']: THREE.MeshStandardMaterial
    ['03_-_Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/goomba/animated_goomba_super_mario_bros.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    actions['Take 001']?.play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="00dd51133e3c4203a068b3fadff534e0fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Goomba" position={[0, 26.038, -2.129]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Body" position={[0.005, 0.047, -21.156]} rotation={[Math.PI / 2, 0, 0]} scale={[0.914, 1, 0.779]}>
                    <group name="Left_Foot" position={[-0.508, -0.703, 0.008]} rotation={[0.001, 0, 0.053]}>
                      <group name="Object_9" position={[1.953, 27.926, 0.603]}>
                        <mesh name="Left_Foot_14_-_Default_0" geometry={nodes['Left_Foot_14_-_Default_0'].geometry} material={materials['14_-_Default']} />
                        <mesh name="Left_Foot_07_-_Default_0" geometry={nodes['Left_Foot_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                      </group>
                    </group>
                    <group name="Right_Foor">
                      <group name="Object_13" position={[1.953, 27.926, 0.603]}>
                        <mesh name="Right_Foor_14_-_Default_0" geometry={nodes['Right_Foor_14_-_Default_0'].geometry} material={materials['14_-_Default']} />
                        <mesh name="Right_Foor_07_-_Default_0" geometry={nodes['Right_Foor_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                      </group>
                    </group>
                    <group name="Object_6" position={[1.953, 27.926, 0.603]}>
                      <mesh name="Body_07_-_Default_0" geometry={nodes['Body_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                    </group>
                  </group>
                  <group name="Head" position={[0, 2.108, 6.77]} rotation={[Math.PI / 2, 0, 0]} scale={[0.914, 1, 0.779]}>
                    <mesh name="Head_10_-_Default_0" geometry={nodes['Head_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
                    <mesh name="Head_1_0" geometry={nodes.Head_1_0.geometry} material={materials.material} />
                    <mesh name="Head_15_-_Default_0" geometry={nodes['Head_15_-_Default_0'].geometry} material={materials['15_-_Default']} />
                    <mesh name="Head_03_-_Default_0" geometry={nodes['Head_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/goomba/animated_goomba_super_mario_bros.glb')
